### ISSUE TITLE
Support for logbook

### ISSUE THREAD

**Issue by skrchnavy** [aurzenligl/pytest-logger#1]
This extension works with python logging module.
Is there a plan to support also logbook (https://logbook.readthedocs.io/en/stable/index.html) logging library?

**Comment by aurzenligl** [comment]
I don't plan to add logbook support, but if you'd like to propose a pull request, I'd be willing to upstream it.

You can also take a look at logbook plugin (I don't know if it logs to filesystem though):
https://pypi.python.org/pypi/pytest-logbook

**Comment by skrchnavy** [comment]
logbook plugin is closer to https://pypi.python.org/pypi/pytest-catchlog, displays logs to console. I like the idea of per test dir log files you have implemented.
I will check, if I can contribute with PR.
