### ISSUE TITLE
log into separate log files bases on log levels when logged into a single logger

### ISSUE THREAD

**Issue by Pranesh3944** [aurzenligl/pytest-logger#15]
Hi, I would like to use a single logger which when used in the scripts should create 2 log files under the test case. For example :  1 log file with all log lines above debug level and one file with all log lines above info level. But, inside the scripts I should be logging only into one logger. Is that possible with the current code  ? Or is it a future enhancement ? Thanks for your help

**Comment by aurzenligl** [comment]
Hello @Pranesh3944, sorry for keeping you waiting. Making two separate files requires making two separate file handlers for this logger. This would allow you to set different levels to each of them, but you wouldn't still be able to set `logging.FileHandler` to allow only logs below certain level, as this is not a feature of stdlib's logging module.

It's possible to allow users to configure custom (file and/or stdout) handlers by `LoggerConfig` object you get in `pytest_logger_config` hook. Then customizations similar to one you propose would be possible.

Just looked at exemplary way to configure loggers/handlers/formatters from Python's stdlib:
https://docs.python.org/2/library/logging.config.html#dictionary-schema-details
and it seems to me that extending `LoggerConfig` by following method would do the trick:
`def add_handlers(self, loggers, handler_classes, formatter_class, level):`
- loggers - logger names
- handler_classes - classes which must inherit from either `logging.StreamHandler` or `logging.FileHandler` as plugin must distinguish them to be able to properly initialize them,

**Comment by aurzenligl** [comment]
Closed due to inactivity.
