### ISSUE TITLE
How to not write to log but append to the log file.

### ISSUE THREAD

**Issue by boonyao1122** [aurzenligl/pytest-logger#16]
Hi, i am new to pytest and also python. I am trying out the example you gave.
Example which i following, [here](https://pypi.org/project/pytest-logger/)

During run my test, logs are always write to my generated log files but not append to end of file. Any how to change to append instead of writing?

**Comment by aurzenligl** [comment]
Hello @boonyao1122, sorry for keeping you waiting. Files are written to a new directory, which is by default a pytest session's tempdir:
https://docs.pytest.org/en/latest/tmpdir.html

Each pytest run (i.e. "session") logs are written anew to a different dir.
```
$ pytest > /dev/null ; ll logs
lrwxrwxrwx 1 aurzenligl aurzenligl 39 Jun 18 02:39 logs -> /tmp/pytest-of-aurzenligl/pytest-3/logs
$ pytest > /dev/null ; ll logs
lrwxrwxrwx 1 aurzenligl aurzenligl 39 Jun 18 02:39 logs -> /tmp/pytest-of-aurzenligl/pytest-4/logs
```

If user chooses own dir, which is the same during each run, files will get overwritten. It doesn't seem to make sense to append to them, as output would get mixed in a way making it difficult to figure out which run given log line comes from.

Does that answer the question?

**Comment by aurzenligl** [comment]
Closed due to inactivity.
