### ISSUE TITLE
Option for root logs dir

### ISSUE THREAD

**Issue by skrchnavy** [aurzenligl/pytest-logger#3]
currently log files are created in directory based on tmpdir fixture.
It would be nice to be able to define root dir, where it is created in command line / configuration file.

workaround is to use `--basetemp`, but it could influence other features.

**Comment by aurzenligl** [comment]
1. Would you prefer:
  - --logsdir, taking path, which will contain what by default e.g. /tmp/pytest-of-X/pytest-Y/logs contains or
  - def pytest_logger_logsdir(config), returning path, as above?
2. I assume this logsdir should be cleared/created at each pytest run, just like --basetemp?

**Comment by skrchnavy** [comment]
I prefer cmdline / configuration option (even for the existing hooks pytest_logger_* better would be to use options).
Regarding cleanup, it would be nice to be able to generate directory per run and keep it, but for now cleared / created dir is OK (less effort for implementation with good value).

I will check if I can contribute in this feature.
