### ISSUE TITLE
Capture all logs?

### ISSUE THREAD

**Issue by alvitawa** [aurzenligl/pytest-logger#43]
Currently you can add a specific logger like so:

```
def pytest_logger_config(logger_config):
    logger_config.add_loggers(['default'], stdout_level='debug')
    logger_config.set_log_option_default('default')
```

Is there a way to simply capture all logs? In our codebase logs are created with `import logging; logging.info()` or use their own defined loggers. I would like to just capture everything that is logged inside of a test (including also for instance logs from a libraries' logger).

**Comment by aurzenligl** [comment]
Empty name indicates root logger, like mentioned here:
https://pytest-logger.readthedocs.io/en/latest/usage.html#low-level-hooks
In your example, you can use `''` instead of `'default'` to add handlers to root logger:
```
def pytest_logger_config(logger_config):
    logger_config.add_loggers([''], stdout_level='debug')
    logger_config.set_log_option_default('')
```

**Comment by alvitawa** [comment]
Thanks! This captures all logs in the tests themselves, but not logs from imported modules (which are pip installed with -e flag). Is there a way to capture those as well? I would like to simply capture all stdout/err if possible.

**Comment by aurzenligl** [comment]
Can you be more specific? I'm not sure whether there is any difference in logging depending on the way in which given module/package is installed. Perhaps you mean logs issued when the module is being imported, i.e. module-level code?

**Comment by alvitawa** [comment]
Thanks for your help. I didn't mean logs issued when the module is being imported. It turns out the logger that wasn't being logged was initialized inside of a fixture. I suppose pytest-logger scans all loggers after import-time so it couldn't see it. I have been able to solve the issue by initializing the logger at import-level instead of in the fixture.
