### ISSUE TITLE
Log redirect

### ISSUE THREAD

**Issue by rajivgup** [aurzenligl/pytest-logger#9]
Hello, 

First I would like to appreciate your work on creating logger plugin that simplifies the logging job when running in a large test environment.
 
I'm trying to use your plugin for my test cases logging. As per its design, it works perfectly so this is not a bug report. However, I have a use case that I would like to see if this plugin can support as a new feature. 

My use case is for some of the testcase I want to redirect logs to the file other than what default, that is being created by this plugin. Let's take an example.

I'm adding the file logging for "app/testcases/test_app.py", which has two test cases under a class MYTESTS,  test_foo and test_bar. Now as per existing plugin features the log files will get created like this.

/tmp/pytest-of-rajiv/logs/app/testcases/test_app/MYTEST.test_foo/pytest_logger
and
/tmp/pytest-of-rajiv/logs/app/testcases/test_app/MYTEST.test_bar/pytest_logger

However, for MYTEST.test_bar I want to redirect the log file to some other location with the different name like this.

/tharnlog/custer1/20180106/test_app/MYTEST.test_bar.log

This something I should be able to control using pytest_test_setup hook based on certain markers.

Currently, the plugin uses nodeid to create the filehandler which will be the by default getting created using full file path from the root directory. There is no option to modify the file path except modifying the --logger-logsdir. Basically, redirect the log file to some other location other than default filehandler. 

After going through your code I feel that it is possible to do it by modifying the LoggerState object and pass it to make handler. 
```

class LoggerPlugin(object):
    def __init__(self, config, logcfg):
        self._config = config
        self._logdirlinks = config.hook.pytest_logger_logdirlink(config=config)
        self._loggers = _loggers_from_logcfg(logcfg, config.getoption('log')) if logcfg._enabled else None
        self._formatter_class = logcfg._formatter_class or DefaultFormatter
        self._logsdir = None
        self._redirectpath = None

```
Modify the state object by influencing this hook. I did the hookwrapper in my conftest to make sure my hook gets called first and I can influence the loggerstate. 

```
    def pytest_runtest_setup(self, item):
        loggers = _choose_loggers(self._loggers, _loggers_from_hooks(item))
        formatter = self._formatter_class()
        item._logger = state = LoggerState(item=item,
                                           stdoutloggers=loggers.stdout,
                                           fileloggers=loggers.file,
                                           formatter=formatter,
                                           redirectpath=self._redirectpath)
        state.on_setup()
```
```
class LoggerState(object):
    def __init__(self, item, stdoutloggers, fileloggers, formatter, redirectpath=None):
        self._put_newlines = bool(item.config.option.capture == 'no' and stdoutloggers)
        self.handlers = _make_handlers(stdoutloggers, fileloggers, item, formatter, redirectpath)
        self.root_enabler = RootEnabler(bool(stdoutloggers and fileloggers))
```
```
def _make_logdir(item, redirectpath=None):
    plugin = item.config.pluginmanager.getplugin('_logger')
    if (redirectpath):
        return plugin.logsdir().join(redirectpath).ensure(dir=1)
    else:
        return plugin.logsdir().join(_sanitize_nodeid(item.nodeid)).ensure(dir=1)

```
```
def _make_handlers(stdoutloggers, fileloggers, item, formatter, redirectpath=None):
    handlers = []
    if stdoutloggers:
        handlers += _make_stdout_handlers(stdoutloggers, formatter)
    if fileloggers:
        logdir = _make_logdir(item, redirectpath)
        handlers += _make_file_handlers(fileloggers, formatter, logdir)
    return handlers

```

And this is how we can influence this hook from conftest 

```
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_setup(item):

    # Let's get the logger plugin
    logger = item.config.pluginmanager.getplugin('_logger')

    #add a File logger
    testname, filename = get_test_file_name(item.nodeid)

    filename = os.path.splitext(filename)[0]
    testnames = (testname, logging.DEBUG)
    logger._loggers.file = [(testnames)]
    newpath = filename
    logger._redirectpath = newpath

    outcome = yield

```
I find this use case is very useful and generic because many of the times we want to record the logging to commonplace for specific reasons. For me, the log files are generated from various test systems in a huge test infrastructure setup. That setup is already generating log files with that naming convention. I can write something as post-test teardown that will copy the log file into that location but that will not be real time and slow down my testing.

I would greatly appreciate your input. I'm also ready to contribute under your guidance.

Thanks,
Rajiv Gupta

**Comment by aurzenligl** [comment]
Hello, would you show how you'd use pytest marks in order to redirect logs? It's certainly possible, I just don't fully understand what user would input in test code and what result that would produce exactly:
  - Would you redirect multiple loggers to single file or one file per one logger?
  - Would destination files be under pytest's tmpdir, or in arbitrary directory?
  - Would logs still reach default files under tmpdir in addition to new destination?

Aside from pytest-mark I see a couple of different approaches which may or may not be a good idea in your situation. Would any of following make sense in your case?

1. use custom fixture adding/removing log handler
```python
@pytest.fixture
def custom_handler():
    hdlr = logging.FileHandler(filename='otherfile', mode='w', delay=True)
    some_logger.addHandler(hdlr)
    yield
    some_logger.removeHandler(hdlr)
    hdlr.close()
```

2. use logdir fixture to write files to tmp log directory
```python
def test_qez(daemon, logdir):
    # write to files under logdir
```

3. use symlink to file within logs directory
```bash
~/projects/study/python-logger $ pytest
# logs are written to subdirectory of /tmp, logs is a symlink to this subdir
~/projects/study/python-logger $ ln -sf logs/test_p.py/test_echo/setup 
~/projects/study/python-logger $ cat setup 
00:00.002 inf setup: session begins
```

**Comment by rajivgup** [comment]
Thanks for your response. Please see inline.

Would you show how you'd use pytest marks in order to redirect logs? It's certainly possible, I just don't fully understand what user would input in test code and what result that would produce exactly:

In test case file:
```
def test_one(log_global):
    log_global.error("This is an Error")

@pytest.mark.SKIP_LOGPUSH
def test_two(log_global):
    log_global.info("This is an Info")

```
Now in conftest
```

@pytest.fixture(scope="function")
def log_global(request):
    if "SKIP_LOGPUSH" in request.note..keywords:
        return logging.getLogger('pytest_logger')
    testname, filename = _sanitized_test_name(request.node.nodeid)
    return logging.getLogger(testname)

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_setup(item):
    if not "SKIP_LOGPUSH" in item.keywords:
        logger = item.config.pluginmanager.getplugin('_logger')
        testname, filename = _sanitized_test_name(item.nodeid)
        filename = os.path.splitext(filename)[0]
        testnames = (testname, logging.DEBUG)
        logger._loggers.file = [(testnames)]
        newpath = filename
        logger._redirectpath = newpath
    yield

def pytest_logger_config(logcfg):
    logcfg.add_loggers(["pytest_logger"], logging.DEBUG, logging.DEBUG)
    logcfg.set_log_option_default("pytest_logger.0")
```
This way it will skip the creation of redirect log files.

Would you redirect multiple loggers to single file or one file per one logger?

One file per one logger

Would destination files be under pytest's tmpdir, or in arbitrary directory?

arbitrary directory provided by the user via input argument. 

Would logs still reach default files under tmpdir in addition to new destination?

No.

I tried to use No. 1 example given by you and to make it the way I want to work it looks like I end up writing my own pytest_logger :(

Other two are not the options.

**Comment by aurzenligl** [comment]
Ok, I get it, you're using fixture to pick logger registered to plugin or logger not registered to plugin. The latter would probably have separate configuration, handler, format, etc. I don't see why `pytest_runtest_setup` would need to be provided in conftest.py, as simply not logging to logger would effectively silence it already.

It's absolutely ok to do this in one's conftest.py/test_*.py files, but I still don't understand what would be expected of pytest_logger in such case? We're talking about altering configuration of plugin on a per-testcase basis using marks and there are many things which could be configured:
  - file/stdout handler levels
  - output directory/file
  - handler formatter
Stopping plugin from creating handlers at all on a, say - `@pytest.mark.logger_ignore` - seems awkward: why configure logger plugin to store data to files and then tell it afterwards not to do so for individual testcases?
